"""finance-calcs — financial calculations for Polars workflows.

Expression metrics accept and return ``pl.Expr`` and are also exposed on a
``.fcalcs`` custom namespace bound to ``pl.Expr`` and ``pl.Series``. Native
indicator kernels, fitted statistics, preprocessing, and post-trade summaries
are explicitly eager APIs over sequences, ``pl.Series``, or ``pl.DataFrame``::

    import finance_calcs  # noqa: F401  — registers the namespace
    import polars as pl

    df.with_columns(
        pl.col("close").fcalcs.log_returns().alias("ret"),
    ).select(
        pl.col("ret").fcalcs.sharpe().alias("sharpe"),
        pl.col("ret").fcalcs.max_drawdown().alias("mdd"),
    )
"""

from __future__ import annotations

__version__ = "0.2.1"

from . import _namespace
from .alpha import (
    conditional_ic,
    forward_returns,
    hit_rate,
    horizon_ic,
    ic_decay,
    ic_ir,
    ic_summary_stats,
    information_coefficient,
    pearson_ic,
    spearman_ic,
)
from .factor import (
    alpha,
    batting_average,
    beta,
    down_alpha,
    down_beta,
    down_capture,
    information_ratio,
    tracking_error,
    up_alpha,
    up_beta,
    up_capture,
    up_down_capture,
)
from .microstructure import (
    amihud_illiquidity,
    effective_spread_bps,
    kyle_lambda,
    order_imbalance,
    quoted_spread_bps,
    realized_spread_bps,
)
from .momentum import (
    adx,
    cci,
    cmo,
    macd_hist,
    macd_line,
    macd_signal,
    minus_di,
    minus_dm,
    mom,
    plus_di,
    plus_dm,
    roc,
    rocp,
    rocr,
    rocr100,
    rsi,
    stoch_d,
    stoch_k,
    trix,
    willr,
)
from .native_kernels import native_adx, native_garch11_variance, native_parabolic_sar
from .overlap import (
    bbands_lower,
    bbands_middle,
    bbands_upper,
    dema,
    donchian_lower,
    donchian_middle,
    donchian_upper,
    ema,
    midpoint,
    midprice,
    sma,
    tema,
    wma,
)
from .portfolio import (
    active_share,
    concentration,
    gross_exposure,
    gross_leverage,
    long_exposure,
    net_exposure,
    short_exposure,
    top_n_concentration,
)
from .post_trade import (
    avg_trade_pnl,
    consecutive_wins_losses,
    cost_attribution,
    cost_per_trade,
    exit_reason_stats,
    extract_round_trips,
    implementation_shortfall,
    long_short_round_trip_stats,
    mae_mfe,
    payoff_ratio,
    profit_factor,
    round_trip_stats,
    sector_round_trip_stats,
    slippage_bps,
    trade_duration_stats,
    trade_size_return_correlation,
    transaction_cost,
    transaction_notional,
    transaction_volume,
    turnover,
    vwap_slippage,
    win_rate,
)
from .preprocessing import neutralize, orthogonalize
from .quantile import (
    assign_quantile,
    long_short_spread,
    mean_return_by_quantile,
    quantile_changed,
    quantile_turnover,
    rank_normalize,
    winsorize,
    zscore,
)
from .regime import fractional_difference, hurst_exponent, regime_signal
from .returns import (
    aggregate_returns,
    annualized_return,
    annualized_volatility,
    cum_returns,
    cum_returns_final,
    log_returns,
    period_bucket,
    returns,
    simple_returns,
)
from .risk import (
    calmar,
    conditional_value_at_risk,
    downside_deviation,
    downside_risk,
    drawdown_series,
    max_drawdown,
    parametric_var,
    sharpe,
    sortino,
    underwater_series,
    value_at_risk,
    volatility,
)
from .stats import (
    common_sense_ratio,
    deflated_sharpe,
    higher_moments,
    kurtosis,
    minimum_track_record_length,
    probabilistic_sharpe,
    sharpe_ci_bootstrap,
    sharpe_with_ci,
    skewness,
    stability_of_timeseries,
)
from .tail import (
    gpd_cvar,
    gpd_var,
    omega_ratio,
    tail_ratio,
    ulcer_index,
)
from .volatility import (
    atr,
    ewma_vol,
    garman_klass_vol,
    natr,
    parkinson_vol,
    realized_vol,
    rogers_satchell_vol,
    true_range,
    yang_zhang_vol,
)
from .volume import ad, adosc, obv

__all__ = [
    "active_share",
    "ad",
    "adosc",
    "adx",
    "aggregate_returns",
    "alpha",
    "amihud_illiquidity",
    "annualized_return",
    "annualized_volatility",
    "assign_quantile",
    "atr",
    "avg_trade_pnl",
    "batting_average",
    "bbands_lower",
    "bbands_middle",
    "bbands_upper",
    "beta",
    "calmar",
    "cci",
    "cmo",
    "common_sense_ratio",
    "concentration",
    "conditional_ic",
    "conditional_value_at_risk",
    "consecutive_wins_losses",
    "cost_attribution",
    "cost_per_trade",
    "cum_returns",
    "cum_returns_final",
    "deflated_sharpe",
    "dema",
    "donchian_lower",
    "donchian_middle",
    "donchian_upper",
    "down_alpha",
    "down_beta",
    "down_capture",
    "downside_deviation",
    "downside_risk",
    "drawdown_series",
    "effective_spread_bps",
    "ema",
    "ewma_vol",
    "exit_reason_stats",
    "extract_round_trips",
    "forward_returns",
    "fractional_difference",
    "garman_klass_vol",
    "gpd_cvar",
    "gpd_var",
    "gross_exposure",
    "gross_leverage",
    "higher_moments",
    "hit_rate",
    "horizon_ic",
    "hurst_exponent",
    "ic_decay",
    "ic_ir",
    "ic_summary_stats",
    "implementation_shortfall",
    "information_coefficient",
    "information_ratio",
    "kurtosis",
    "kyle_lambda",
    "log_returns",
    "long_exposure",
    "long_short_round_trip_stats",
    "long_short_spread",
    "macd_hist",
    "macd_line",
    "macd_signal",
    "mae_mfe",
    "max_drawdown",
    "mean_return_by_quantile",
    "midpoint",
    "midprice",
    "minimum_track_record_length",
    "minus_di",
    "minus_dm",
    "mom",
    "native_adx",
    "native_garch11_variance",
    "native_parabolic_sar",
    "natr",
    "net_exposure",
    "neutralize",
    "obv",
    "omega_ratio",
    "order_imbalance",
    "orthogonalize",
    "parametric_var",
    "parkinson_vol",
    "payoff_ratio",
    "pearson_ic",
    "period_bucket",
    "plus_di",
    "plus_dm",
    "probabilistic_sharpe",
    "profit_factor",
    "quantile_changed",
    "quantile_turnover",
    "quoted_spread_bps",
    "rank_normalize",
    "realized_spread_bps",
    "realized_vol",
    "regime_signal",
    "returns",
    "roc",
    "rocp",
    "rocr",
    "rocr100",
    "rogers_satchell_vol",
    "round_trip_stats",
    "rsi",
    "sector_round_trip_stats",
    "sharpe",
    "sharpe_ci_bootstrap",
    "sharpe_with_ci",
    "short_exposure",
    "simple_returns",
    "skewness",
    "slippage_bps",
    "sma",
    "sortino",
    "spearman_ic",
    "stability_of_timeseries",
    "stoch_d",
    "stoch_k",
    "tail_ratio",
    "tema",
    "top_n_concentration",
    "tracking_error",
    "trade_duration_stats",
    "trade_size_return_correlation",
    "transaction_cost",
    "transaction_notional",
    "transaction_volume",
    "trix",
    "true_range",
    "turnover",
    "ulcer_index",
    "underwater_series",
    "up_alpha",
    "up_beta",
    "up_capture",
    "up_down_capture",
    "value_at_risk",
    "volatility",
    "vwap_slippage",
    "willr",
    "win_rate",
    "winsorize",
    "wma",
    "yang_zhang_vol",
    "zscore",
]
